---
title: "Drawing the Line: Judicial Review and Gerrymandering"
author: "Levi Moneyhun"
date: "Submitted May 5, 2019"
output:
 tufte::tufte_html: 
  number_sections: true
bibliography: thesis_bibliography.bibtex
link-citations: yes
csl: chicago-fullnote-bibliography.csl
---

```{r setup, include=FALSE}
library(tufte)
setwd("/Users/levimoneyhun/Code/moneyhun.github.io/")
options(htmltools.dir.version = FALSE)
```

`r newthought('Democracy faces')` threats on many sides. This essay concerns the proper balancing of two such threats: judicial review and gerrymandering. Judicial review, in which non-popularly elected judges declare acts by the legislature and executive to be unconstitutional, “thwarts the will of representatives of the actual people of here and now.”^[@Bickel-1962, 17.] But judicial review also often serves to correct democracy’s worst mistakes. Judicial review is responsible for ending school segregation in _Brown v. Board of Education_ and for ending the denial of marriage equality in _Obergefell v. Hodges_.^[Brown v. Board of Education, 347 U.S. 482 (1954); Obergefell v. Hodges, 576 U.S. __ (2015).] Potentially, it could even help fight the threat of gerrymandering---the manipulation of representative district boundaries in order to derive a political advantage. 

By distorting the process of geographic representation, gerrymandering “prevents a just recognition of the expressed will of the legal voters” and either “disenfranchise[s] the majority or [...] secure[s] it an influence disproportionate to its size.”^[@Griffith-1907, 8.] As gerrymandering tends to protect incumbents and other dominant political interests, legislatures are unlikely to act against gerrymandering. Further, ordinary processes of representative accountability are unlikely to be effective with regard to gerrymandering. Thus, it not only threatens democracy but also appears relatively invulnerable to ordinary democratic solutions. 

In this essay, I will argue that courts should engage in judicial review of partisan gerrymandering. While acknowledging that many forms of judicial review pose a legitimate threat to democracy, I will argue that there is a class of procedural questions---such as the issue of gerrymandering---where judicial review does not threaten, but instead enhances, democratic legitimacy. Further, I will claim that judges should embrace judicial review in these areas.

Although some points made in the paper may apply broadly, I will discuss judicial review and representative democracy largely as they are structured at the federal level in the United States. Key features include (a) geographic representation via winner-take-all single-member districts, (b) two major political parties, (c) an appointed (rather than elected) judiciary, and (d) a written constitution. This paper is fundamentally a philosophical rather than a legal argument, seeking to answer the question in the general context of the U.S. political structure, rather than the specific context of current legal precedent on the issue. Additionally, I will not address the issue of racial gerrymandering, which greatly complicates modern legal questions regarding partisan gerrymandering. 

Although the United States Supreme Court has never struck down a districting map on the basis of impermissible partisan gerrymandering, it has often come close. In _Vieth v. Jubelirer_, a clear majority agreed that gerrymandering constituted a legitimate harm to democracy. Four justices claimed that, despite the legitimate harm, there was no judicially manageable standard to adjudicate partisan gerrymandering cases. Four other justices disagreed, claiming that the standards proposed were judicially manageable. The last of the nine---the pivotal vote against the plaintiffs---agreed that no manageable standard had been presented, but held out hope that such a standard may be developed in the future, narrowly preventing the issue from being closed for future consideration by _stare decisis_.^[Vieth v. Jubelirer, 541 U.S. 267 (2004).]

The Supreme Court again considered the issue of partisan gerrymandering in 2017, hearing argument in _Gill v. Whitford_ and _Benisek v. Lamone_. In neither case, however, did the court reach the substantive question at issue: _Gill_ was dismissed for lack of standing and _Benisek_ was dismissed as unripe.^[Gill v. Whitford, 585 U.S. \__ (2018) (138 S. Ct. 1916); Benisek v. Lamone, 585 U.S. __.] (2018) (138 S. Ct. 1942).] Even now, the Supreme Court continues to consider the issue, hearing arguments in _Rucho v. Common Cause_ and _Lamone v. Benisek_ on March 26, 2019.^[Rucho v. Common Cause, No.18-422 (U.S., argued Mar. 26, 2019); Lamone v. Benisek, No. 18-726 (U.S., argued Mar. 26, 2019).] The Court’s reticence to decide this issue stems from two considerations: first, that adjudicating gerrymandering cases may force the court to decide fundamentally political questions best left to the legislature; second, that no manageable standards exists to identify and redress the harm alleged by plaintiffs in gerrymandering cases. A key goal of this essay is to argue that these hesitations are unfounded and that the Court should rule definitively in favor of the plaintiffs in cases like these. 

My argument will proceed as follows. `r newthought('section')` 1 will begin by introducing the general notion of democratic legitimacy which will guide subsequent argument. In `r newthought('section')` 2, I will explore the problem of judicial review with respect to varying conceptions of democratic legitimacy, finding that these objections are strongest under a procedural account of legitimacy. On the basis of this finding, `r newthought('section')` 3, will propose and defend a narrow conception of judicial review compatible with a procedural conception of democratic legitimacy. `r newthought('section')` 4 will examine the problems gerrymandering poses for democratic legitimacy. In `r newthought('section')` 5, I will argue that the proposed conception of legitimacy-enhancing judicial review includes judicial review of partisan gerrymandering, and that judges should therefore embrace intervention on this issue. Together, `r newthought('sections')` 1--5 comprise the first-order case for my argument. In `r newthought('section')` 6, I will address the second-order objection that no judicially manageable standard exists for the adjudication of partisan gerrymandering cases by proposing and defending a possible standard. 

# Understanding Legitimacy

`r newthought('The term')` “legitimacy” is widely used with varying meaning. In this essay, I will limit discussion to a narrow enough conception of legitimacy to make discussion intelligible. But, because my argument does not depend on a particular theory of legitimacy, I will not further narrow legitimacy to any particular theory. Rather, I will consider many possible accounts of legitimacy. This section aims only to clarify what subsequent references to legitimacy mean, rather than to universally define what legitimacy is. Two key distinctions will be made: first, that legitimacy refers to institutions rather than outcomes; second, that it refers to a scalar, rather than binary, attribute. 

Legitimacy, as relevant to this essay, is fundamentally tied to the question: “what kind of political institutions ought to be supported by individuals?”^[@Brinkmann-2016, 20.] It may be understood as the extent to which political institutions normatively deserve the support of their constituents. In this understanding, it is institutions, rather than outcomes, which are the relevant unit of analysis for legitimacy. The outcomes which an institution generates, as well as the processes by which it does so, are key inputs to answering questions of legitimacy, but these outcomes themselves cannot be coherently called legitimate or illegitimate. The precise connection between outcomes, processes, and legitimacy varies across the several potential conceptions of legitimacy which will be discussed later. 

Legitimacy here will not be understood as binary distinction between legitimate and illegitimate institutions. Instead, legitimacy is a scalar attribute describing the extent to which institutions approach “an ideal for how the members of a democratic constituency ought to make decisions.”^[@Peter-2009, 1.] This scalar understanding of legitimacy is crucial for the topic of this essay: the resolution of a tradeoff between two threats to democratic legitimacy. A binary conception of legitimacy precludes discussion of balancing multiple threats to legitimacy. Such a conception leads instead to the uninteresting conclusion that American political institutions simply are either legitimate or illegitimate and that neither gerrymandering nor judicial review, alone or together, will shift the balance from one to the other. 

Within this essay, legitimacy will refer to a scalar quality of institutions. Beyond this clarification, I will not make any more ambitious claims of which particular conception of legitimacy we should accept as correct. Instead, I will explore a variety of conceptions and orient my argument around the least controversial account of legitimacy which provides strong grounds for objection to judicial review. I explore the instrumental view (that legitimate institutions are those which produce the best possible outcomes) and the proceduralist view (that legitimate institutions are those which create outcomes through fair procedures). Finding that the proceduralist view allows for the strongest objection to judicial review, I will address my arguments primarily to the procedural view. 

# The Problem of Judicial Review

`r newthought('To understand')` the circumstances under which judicial review may be legitimate, we must identify how and why it is generally problematic. In discussing judicial review, I will consider primarily what Jeremy Waldron calls “strong judicial review,” in which courts effectively have the power to negate legislative actions.^[@Waldron-2006 at 1354.] The vast majority of court rulings, even at the level of the Supreme Court, do not involve judicial review. Courts are tasked with interpreting and applying statutes. It is only in rare cases that courts, in interpreting and applying statutes, must consider their constitutionality. As such, this essay is oriented to only a small, although vital, portion of the Court’s function. 

In the political structure of the United States, with popularly elected representative legislators and an appointed, rather than elected, judiciary, this form of judicial review is at tension with democratic principles. Although the legislature, like the judiciary, is somewhat divorced from the actual popular will, it is clearly more representative of and more accountable to the people. As such, judicial review is the exercise of power by a less democratic institution over a more democratic institution. The extent to which this poses a problem for democratic legitimacy depends on one’s conception of democratic legitimacy. Here, I will look at instrumental and procedural accounts of legitimacy. 

## Instrumental Legitimacy 

Under an instrumental conception of legitimacy, “what renders the democratic form of government for a nation morally legitimate (when it is) is that its operation over time produces better consequences for people than any feasible alternative mode of governance.”^[@Arneson-2003 at 122.] The instrumental position is not necessarily committed to the claim that more democratic forms of government are more legitimate than less democratic alternatives. The central normative claim of instrumentalism---that the government which produces the best outcomes is the most legitimate---can generate a specific claim regarding Government A’s legitimacy only in conjunction with the empirical claim that Government A produces better outcomes than its alternatives. The central claim of instrumentalism does not commit it to support of democracy, let alone to any particular structure of democracy. Rather, any specific commitment occurs as a result of an empirical claim regarding the outcomes produced by a particular set of governing arrangements. 

The instrumental position considers the fundamental questions of politics---e.g., what justice demands, what well-being entails, what rights exists---to be normatively settled, even while disagreement may still exist as an empirical fact. Prior to evaluating which institutions lead to the best outcomes, an instrumentalist must accept some conception of the best outcomes. While the general instrumentalist position does not embed any particular theory of justice, morality, or well-being, any applicable incarnation of the instrumentalist view must take a stance on these key issues. 

On the controversial question of same-sex marriage, for example, applicable instrumentalism cannot be neutral. It must either claim that the legality of same-sex marriage is a superior outcome to its prohibition, or vice versa. Considering this question to be settled, the instrumentalist cares not whether the outcome is reached by legislative processes or by the Supreme Court overruling the legislative process. All that matters is that the correct outcome is reached. 

Within the instrumental position, crafting a valid argument for judicial review would be philosophically (although not empirically) trivial. However, the premises on which this argument must rest would unworkably controversial for the purposes of this essay. Before making the argument (even if we accept the key instrumentalist claim, not itself lacking in controversy), I would have to propose a definition of the best outcomes (which would entail taking a stance on many of the most controversial issues in political philosophy) and defend an empirical claim that judicial review would facilitate the attainment of these outcomes. The conclusion follows from these premises by mere syllogism, but these premises cannot be established without great challenge.  

Because the general instrumental view cannot by itself sustain an objection to judicial review and because the normative and empirical claims supporting a specific instrumental view capable of generating an objection to judicial review are controversial and difficult to prove, it would not be productive to frame my argument around an instrumental account of legitimacy. Instead, I will divert focus away from instrumental accounts of legitimacy in favor of other accounts. 

## Procedural Legitimacy

Procedural conceptions of legitimacy provide stronger grounds to object to judicial review. These accounts, valuing democracy intrinsically, ground legitimacy not in the outcomes attained but instead in the processes generating these outcomes. Beginning from an acceptance of pluralism, the proceduralist position does not claim prior knowledge of the end which democracy should serve. Instead, it recognizes significant disagreement about best outcomes and about how best to reach these outcomes, as well as disagreement about rights and how to protect these rights. Given this fact of disagreement, democracy serves as a mediator of conflict---an instrument not towards the achievement of a pre-identified end but instead towards the identification of ends which may be acceptable to a pluralistic society. 

A defense of this general view---that disagreement is not merely an unfortunate bump in the road to an ideal polity but rather is the whole of politics and an important object of political philosophy---is presented by Jeremy Waldron in Law and Disagreement. The argument begins with the assertion: “there are many of us, and we disagree.”^[@Waldron-1999, 1.]  From the perspective of a legislator, he writes^[@Waldron-1999, 23.]

>We do not wait for disagreements about social justice to be settled _outside_ the legislature before we begin our activities. Instead, we do our work by _internalizing_ those disagreements, by building them into the institutional structure of our assembly, [...] indeed by making them part of the process of our law-making. [...] The modern legislature is an assembly of the representatives of the main competing views in society, and it conducts its deliberations and makes its decisions in the midst of the competition and controversy among them.

Under this view, legislative procedures are crucially different from their judicial counterparts. While both involve the presentation of competing views on an issue to enable the resolution of the issue, courts sharply distinguish “between the parties and the decision-maker (the judge)” while legislatures contain no such distinction.^[@Waldron-1999, 23.] Judicial proceedings are stylized as parties’ presentation of competing views to an impartial arbiter who, considering the arguments before him, renders an objective and decisive verdict. Legislatures, by contrast, embrace the fact that the parties to issues will not only decide these issues but will do so “explicitly on the basis of [their] well-advertised opposed and divisive views about the issues under consideration.”^[@Waldron-1999, 23.]

The key foundation of the proceduralist position---the premise that distinguishes it from an instrumental view---is that respecting individuals requires respecting disagreement and that respecting disagreement requires valuing procedures _per se_ rather than as instruments to outcomes. Waldron notes, however, that this position does not necessitate moral relativism: “As long as objective values fail to disclose themselves to us [...] in ways that leave no room for further disagreement [...] all we have on earth are _opinions_ or _beliefs_ about objective value.”^[@Waldron-1999, 111 n. 62.] Thus, questions of legitimacy have to do with how we treat beliefs about justice, not the truth about justice.

Procedural accounts of legitimacy may take on many different forms. Fabienne Peter proposes a taxonomy along two dichotomies: aggregate versus deliberative and “pure” versus “rationalist”.^[@Peter-2007 at 331. Peter also distinguishes between epistemic and non-epistemic variants of each of these conceptions of legitimacy, but this distinction is unimportant for the purpose of my argument.] Aggregative models take a narrow conception of procedure as simply the process of combining individual preferences into a collective choice. Deliberative models take a more expansive conception of procedure, highlighting the process of public discussion in which preferences are formed. Pure conceptions take institutions to be “legitimate if the democratic process satisfies certain conditions,” typically conditions of political fairness and equality; rationalist conceptions add the further requirement of “rationality of the outcomes.”^[@Peter-2007 at 332.] 

Rationalist theories, in admitting extra-procedural conditions on legitimacy, acknowledge the potential legitimacy of judicial review. Pure theories, however---whether aggregative or deliberative---provide strong grounds for objection to judicial review. 

For aggregative theorists, institutions are legitimate when they fairly aggregate citizens’ preferences. Judicial review overturns the aggregation of citizens’ preference in favor of the aggregation of a small panel of judges’ preferences. Even while electoral processes fall short of true fairness in aggregation, they should be expected to approximate it better than judicial processes. Even at their worst, electoral processes represent an attempt at aggregation; the judicial process lacks any pretense of aggregation, and its results resemble those of aggregative process only by chance judicial whim. As such, judicial review has clear de-legitimizing force in an aggregative conception of democracy. 

Though vastly different than aggregative conceptions of procedural legitimacy, the deliberative view seems to offer the same answer on the issue of judicial review. A deliberative theory does not subtract any of its aggregative counterpart’s demands---rather, it adds additional demands---so it does not undo its first order objections to judicial review. Deliberative proceduralism insists upon the importance of the constructive functions which give rise to preferences, but it does not relax its insistence on the fair aggregation of these preferences. 

As pure proceduralist conceptions of legitimacy---both aggregative and deliberative---have the strongest objections to judicial review, I will frame my argument primarily with respect to them. In the next section, I will examine the foundations of these conceptions to guide the development of a procedural theory of judicial review consistent with democratic legitimacy. 

# A Procedural Theory of Judicial Review

`r newthought('Having described')` the basic features of instrumental and procedural accounts of legitimacy, I will now examine the underlying principles that ground these accounts in order to inform the development of a theory of legitimacy-enhancing judicial review, focused toward review of political processes.^[This theory of judicial review is greatly informed by @Ely-1980.]

To understand procedural conceptions of legitimacy, one must first understand the assumptions underlying the instrumentalist conceptions to which these theories are responding. Inherent in an instrumentalist conception of legitimacy is the ability to identify correct outcomes. To defend the instrumentalist view, one must propose an objective standard to do so---a demanding argumentative task. The instrumentalist may try instead to propose that good outcomes may be defined subjectively as those outcomes which society prefers over other outcomes, but this ultimately reduces to an aggregative form of proceduralism. 

Proceduralist theories claim to operate without necessitating the prior acceptance of what is right. Instead, they acknowledge “disagreements which cannot be reconciled” and claim that, in the absence of agreement on a best solution, “there is no other justification for a particular decision [...] other than it being the result of a fair process.”^[@Peter-2007 at 335.]  While not faced with the task of defining the right, the proceduralist must propose and a defend a notion of fairness. I will take these notions of fairness---the grounding principals of procedural conceptions of legitimacy---as the key guiding principles for the development of a legitimacy-enhancing theory of judicial review. 

## Aggregative Fairness

In the aggregative conception, democracy can be viewed as a decision machine which takes constituents’ preferences as inputs and generates political decisions as outputs. Under such a conception, fairness consists in the proper functioning of this machine. Identifying this proper function, however, proves difficult. Research in social choice theory finds that such a “decision machine” cannot be perfectly designed.^[_See_ @Arrow-1950, proposing an impossibility theorem: no ranked voting system can simultaneously satisfy the conditions of unrestricted domain, non-dictatorship, and the independence of irrelevant alternatives.] The mathematical impossibility of a perfect mapping from individual preferences to collective decisions does not, however, preclude the existence of desirable and undesirable features in fair aggregative procedures. 

I propose two desirable features, proceeding from an intuitive understanding of fairness: first, equality---aggregative procedures should not weigh any constituent’s preferences greater or less than those of another; second, neutrality---aggregative procedures should not favor one outcome over another.^[These conditions are inspired by @May-1952. His mathematical conceptions of these conditions prove ill-suited for analysis of multi-level systems. As such, I will focus my argument around broader notions of these conditions.]  In a simple direct vote, these conditions identify majority rule as a fair procedure.^[@May-1952 at 682.] In more complex systems---e.g., a legislature of elected representatives---these conditions are insufficient to identify a specific set of fair procedures. Nevertheless, they may inform discussion of procedural unfairness, thus grounding discussion of procedural legitimacy. 

Accepting equality and neutrality as conditions for fair procedures, democratic governance is legitimate insofar as its procedures meet these conditions. Under this view, judicial review diminishes legitimacy. Though legislatures may not perfectly satisfy these conditions, they come far closer than do courts. Representative elections and the resulting legislative bodies may be flawed, but they constitute a genuine attempt at an equal, neutral aggregative process. The judicial sphere has neither the appearance nor effect of aggregating popular preference into collective decisions. Like legislatures, courts render decisions with the force of political outcomes. But instead of taking preferences as inputs, courts take factual and textual controversies, generating a decision through interpretation and adjudication rather than aggregation. Although judicial review is a direct affront to procedural legitimacy, it may nonetheless have a positive net effect on legitimacy when it strikes down unfair procedures.  

### Legitimacy-enhancing review and Baker v. Carr

Take the case of _Baker v. Carr_, in which the Supreme Court considered the question of legislative apportionment---i.e., the number of citizens represented by each member of the House of Representatives.^[Baker v. Carr, 369 U.S. 186 (1962).] The demands of fairness are simple in a single constituency-wide vote, becoming more complicated in representative political procedures. However, fairness’ demands are still informative in this context. The requirement of equality clearly requires citizens to be counted equally within elections for representatives, resulting in simple majority rule. But citizens must also be counted equally _across_ elections. This requirement suggests that the demands of legitimacy may impose requirements on the apportionment of representation. In order for citizens to be counted equally across elections, representatives must represent equal numbers of citizens. This echoes the “one person, one vote” standard later articulated by the Supreme Court in a related case, _Reynolds v. Sims_.^[Reynolds v. Sims, 37 U.S. 533 (1964). _Baker v. Carr_ held that apportionment was a justiciable issue. It was not until _Sims_, however, that the court declared a standard for adjudicating the issue.]

What then justifies the Supreme Court’s intervention here? In overruling the decision of a more legitimate institution, the Court does genuine harm to democracy, on the purely procedural account. Judicial review cannot be justified merely by the imperfection of representative democratic procedures. However, the decision here overruled---Tennessee’s plan of apportionment, which weighted the votes of urban voters (often African-American and liberal) far less than those of rural voters (often white and conservative)---itself distances democracy from its ideal. This plan of apportionment violated equality by diluting the votes of urban voters relative to their rural counterparts and violated neutrality by skewing the process of representation to favor conservative politics. In exercising judicial review, striking down this plan of apportionment, the Court harms legitimacy through the act itself, but it enhances it through its effects. 

### Legitimacy-enhancing review generally

This example suggests a general class of judicial review which may be legitimacy-enhancing rather than legitimacy-degrading. To understand the bounds of this class, we must examine the two key claims of the aggregative proceduralist view of legitimacy: 

1.	People genuinely disagree on the issues of politics. 
2.	Disagreements should be resolved into political decisions by fair processes of aggregation. 

When judicial processes supersede aggregative processes on issues of substantial disagreement, legitimacy is diminished. From the procedural account of legitimacy, the Court’s decision in Roe v. Wade, overturning state bans on abortion diminishes democratic legitimacy.^[Roe v. Wade, 410 U.S. 113 (1973).] But a decision finding abortion to be illegal, even in the absence of state bans, would constitute equal harm. The issue of abortion embeds controversies of the extent of women’s rights, the definition of life, and the nature of dependents’ rights. A procedural view of democracy demands that issues such as these---due to the vast and genuine disagreement about them---be decided democratically, rather than through the judicial process.

Apportionment, at issue in _Baker v. Carr_, is not without controversy. The question of whether representation must be apportioned by population or by geography animated the United States’ founding debates, ultimately resulting in the compromise of a bicameral legislature. However, the controversy here is of a different nature: it does not concern the substantive questions which the political process is designed to answer, but instead concerns the political process itself. Additionally, though apportionment created significant controversy at the time of the founding, the depth and intensity of this controversy at the time of _Baker v. Carr_ are significantly weaker than those regarding the issue of abortion. Disagreement on abortion continues to inspire constant active protest by both sides, including 42 bombings and 186 arsons of abortion clinics since 1977.^[[40 Years of Attacks on Abortion Clinics, Mapped (Vox.com).](https://www.vox.com/2015/12/1/9827886/abortion-clinic-attacks-mapped)] Disagreement regarding apportionment---whether we are a nation of distinct geographies or a nation of people---was somewhat settled during reconstruction and the New Deal era, as the United States moved from a system of dual federalism to a much more national system.^[_See_ @Gerston-2007.] Disagreement remained on this issue but, unlike the issue of abortion, did not inspire constant and occasionally violent protest, contemporaneous with or subsequent to the Court’s decision in _Baker v. Carr_. 

Further, in addition to being less passionate, it is likely that disagreement on apportionment (and other similar procedural issues) is less genuine---i.e., it is actually a proxy for disagreement on a different issue or set of issues. Tennessee legislators may have genuinely believed that political fairness demanded that citizens’ votes not be weighted equally with respect to the election of legislative representatives. More likely, however, they viewed this dilution as a strategy to achieve a substantive political end: stemming the advancement of African-American civil rights. 

Revisiting the first principle stated above, we see that the aggregative proceduralist position recognizes the intensity and legitimacy of disagreement on questions of politics. However, it should afford less respect to disagreement on issues of procedure than on issues of substance. These procedural disagreements are of a different nature, excite less acrimony and passion, and may be less genuine. Because of these differences, the aggregative position may be able to coherently endorse non-democratic resolution of procedural questions.  

The second claim of the aggregative position insists that disagreements be resolved by fair processes of aggregation. To demand that disagreements about the political process be resolved by the political process, however, appears improper. On the issue of political procedures, the existing process will naturally render a self-reinforcing verdict. Consider again the case of _Baker v. Carr_. Suppose that the Tennessee legislature were asked to decide whether legislative districts must contain equal populations. Having been elected by districts of vastly unequal population, such that rural constituents’ interests enjoyed much more representation in the legislature, Tennessee legislators have little reason to demand equal representation. In both their personal quests to maximize power and their civic quests to further their constituents’ interests, the dominant powers in the legislature necessarily stand to lose from demanding a political procedure contrary to that which elected them. The representative legislature is poorly situated to fairly and competently consider issues of the political process. 

The electoral process, often the cure to problems of imperfect representation, fares not much better here. Unlike on the issue of taxation, for example, elections here have little force in correcting the misdeeds of the legislature. If the legislature were to increase (or decrease) taxes beyond the level aggregately preferred by its constituents, the next election would provide an opportunity for new candidates, vowing to levy taxes consistent with popular preference, to challenge and defeat incumbents. The political process here, addressing a substantive question, functions as a pendulum: while the weight may be pulled from the center of aggregative popular preference, the gravitational pull of electoral accountability will eventually (though often not immediately) draw it back.

While it may function as a pendulum on substantive questions, the political process acts instead as a feedback loop on issues of procedure. A representative process which affords less weight to the preferences of urban voters will not vindicate these neglected interests. Instead, the rural legislative dominance engendered by this unequal apportionment will lead only to further erosion of rural interests, both substantial and procedural. By controlling the political process, “the ins are [capable of] choking off the channels of political change to ensure that they will stay in and the outs will stay out.”^[@Ely-1980, 103.] 

The aggregative position insists that political questions be decided through the political process. However, this demand appears suited only for substantive political questions. Even if it would be more legitimate for political process to properly resolve procedural questions, the nature of politics makes this very difficult. The natural structure of the political process hinders rather than encourages proper resolution of procedural issues. Democracy’s relative inability to cure its own procedural faults enhances the justification for judicial action in this sphere. Judges are well suited to serve this procedural review function. However, their advantage “isn’t so much one of expertise as it is one of perspective.”^[@Ely-1980, 102.]  Here, the judiciary’s role is akin to that of a referee, “interven[ing] only when one team is gaining unfair advantage, not because the ‘wrong’ team has scored.”^[@Ely-1980, 103.] Judges, not being players of the game, are uniquely well-suited to serve this refereeing function.

Although judicial review harms legitimacy in supplanting the political process in deciding an issue of political disagreement, this harm is lesser for procedural issues than for substantive issues. As such, judicial review of legislative infringements of fair political processes may enhance rather than degrade legitimacy and therefore be allowable under an aggregative proceduralist conception of legitimacy. 

## Deliberative Fairness

The deliberative procedural account of legitimacy rests on a much thicker conception of fairness than the aggregative conception. Per the deliberative account, the site of democracy extends beyond the instruments of aggregation---elections, representative legislatures, etc.---and into the sphere of public discourse. As such, the demands of fairness extend not only to aggregative processes but instead to a much wider range of social functions. Jürgen Habermas claims that it is not sufficient to simply have fair procedures for deliberation and decision. Instead, the principles underlying fair deliberation must “expand into a self-organization of society and penetrate [society’s] complexity as a whole.”^[@Habermas-1996, 305. Italics from original omitted.] Such a deliberative account of fairness places conditions not only on actual political procedures but also on the whole of the informal public sphere---i.e., on all of society. 

In addition to having a broader reach, the conditions for deliberative legitimacy are also far more demanding than those for aggregative legitimacy. Grounding legitimacy in discourse and will formation, the deliberative conception requires that all enjoy equal capacity to shape and influence public discourse and are equipped with the necessary faculties to develop and articulate their views in open debate.^[@Habermas-1996, 315]  Legitimacy thus requires a substantively fair society, in which citizens enjoy positive entitlements---e.g., civic education and sufficient economic prosperity to enable autonomy and prevent coercion---and are not only politically but also socially equal. The distinction between process and substance somewhat erodes under this view. Though the deliberative position maintains that procedures, not substantive outcomes, are the grounds for legitimacy, its all-encompassing view of the political process renders procedural fairness so broad as to have the effect of substantive constraints. As a result, a theory of judicial review framed around a deliberative conception of legitimacy would embrace an excessively broad range of judicial review as being legitimacy-enhancing. 

The deliberative account of procedural legitimacy commands not only that all preferences are equally weighted in aggregation but that all are on equal footing to confront one another in social processes of deliberation. Thus, deliberative legitimacy may require not only majority rule but also a vast array of programs designed to achieve social equality: e.g., equally provided public education, progressive taxation to achieve economic equality, and publicly established fair debate fora. These demands, though procedural in their justification, are so broad as to become substantive in nature. 

The more expansive deliberative view invites additional controversy which is not necessary to sustain my argument. The class of judicial review which is legitimacy-enhancing under an aggregative view is also legitimacy-enhancing under the deliberative view. By broadening the requirements for legitimacy, a deliberative account only broadens the range of acceptable judicial review and cannot diminish its reach. These broader requirements, even if correct, are nonetheless controversial. Because the more minimal requirements of the aggregative view are sufficient to sustain my argument, I will orient my argument primarily, but not exclusively, to the aggregative view. 

## Distinguishing Process and Substance

This theory of judicial review rests on a distinction between substantive and procedural questions, leaving it susceptible to a critique that there is no such cognizable distinction. A deliberative view of legitimacy, I argue, results in significantly blurring of process and substance. Laurence Tribe, arguing that the two can never be distinct, writes^[@Tribe-1980 at 1070--1071]

>If process is constitutionally valued, therefore, it must be valued not only as a means to some independent end, but for its intrinsic characteristics: being heard is part of what it means to be a person. Process itself, therefore, becomes substantive. There is a curious irony here. One who holds that constitutional law should aim chiefly to perfect process is apparently unable to treat process as itself valuable. For, to see why process would _itself_ be valuable---intrinsically so---is to see why the Constitution is inevitably substantive. Instead, the process-perfecter must treat process as ultimately instrumental, as but a means to other ends, and thus must regard as secondary what he would at the same time celebrate as primary.

Tribe correctly notes that process is valued _per se_ under such a conception of judicial review, and particularly under the procedural account of legitimacy in which my argument is framed. However, his argument---that process and substance are necessarily co-original and that any attempted distinction falls victim to problems of circularity---does not follow. Substance may coherently both precede and follow from process. 

The apparent difficult in separating process and substance rests on a failure to distinguish two forms of substance, which I will call first-order substance and second-order substance. First-order substance consists of the substantive commitments which are embedded in the structure of democratic governance---i.e., the basic principles that define the nature of a democratic political society. These commitments should be fairly minimal and close to universally accepted. Second-order substance consists of actual governing actions---e.g., the prohibition of abortion, the desegregation of schools, or the elimination of the capital gains tax. As illustrated by the examples given, second-order substance is likely to be controversial, commanding acceptance only be virtue of having resulted from fair procedures. 

First-order substance, Tribe correctly notes, does precede process. A commitment to fair processes of aggregation or deliberation indeed rests on basic first-order substantive claims. But the fact that notions of fair aggregation and deliberation follow from substantive commitments does not render these notions substantive. While first-order substance precedes process, second-order substance follows from process. As such, process is the mechanism by which first-order substance is mapped onto second-order substance. The Court must rely on prior acceptance of less controversial first-order substantial propositions to enforce a fair process for resolving more controversial second-order substantial questions. To ensure that this review remains a procedural rather than substantive character, these first-order substantive commitments must be minimal such that it is primarily the procedural demands which follow from these commitments, rather than the commitments themselves, which ground the Courts’ decisions. 

Many issues embed procedural and substantive components in mixed degree. As such, the theory of judicial review advocated here will not be fully determinate in all cases. However, there still exists a narrow range of clearly procedural issues where judicial review may enhance, rather than diminish, legitimacy. In the following sections, I will argue that partisan gerrymandering falls within this range.  

# The Problem of Gerrymandering

`r newthought('Gerrymandering presents')` two key problems for democracy: first, it distorts the representation of the popular will; second, it corrupts the deliberative function of democracy. Before examining the problems posed by gerrymandering, I will explore how it functions.

## How Gerrymandering Works

Traditional models of partisan gerrymandering operate jointly through packing and cracking. Party A, the dominant party, packs Party B voters into a small number of districts in which they enjoy supermajority victories, while simultaneously cracking other Party B voters across a larger number of districts, in which Party A will enjoy small but safe majorities, thus ensuring Party A’s continued electoral dominance.^[@McGann-2016, 62.] The object of this scheme of packing and cracking is to waste as many of the opposing party’s votes and as few of the favored party’s votes as possible. A vote is wasted if cast for a losing candidate, or if cast for a winning candidate in excess of the amount needed for that candidate to win.

If political affiliations were uniformly distributed across geography, such a tactic would be impossible. Gerrymandering leverages patterns in political geography to create partisan advantage. To take maximum advantage of geography often necessitates drawing strangely shaped districts. These odd shapes form the basis for the etymology of the gerrymander---a portmanteau of “salamander” and the last name of Elbridge Gerry, who had signed a redistricting bill creating a conspicuously serpentine district near South Essex, Massachusetts.^[@Griffith-1907, 18.]

## Distortion of Representation

The results of the 2012 Congressional elections provide evidence of how gerrymandering distorts the representation of the popular will. Following the 2010 midterm elections, in which the Republican Party not only gained control of the United States House of Representatives but also gained full control of 11 state legislatures, 25 state legislatures were fully controlled by the Republican Party, 16 were fully controlled by the Democratic Party, and nine were either divided or non-partisan.^[[2010 Post-Election Party Control of State Legislatures (National Conference of State Legislatures)](http://www.ncsl.org/research/elections-and-campaigns/2010-postelection-control-of-legislatures.aspx); [2010 Election: Legislature Party Control Switch (National Conference of State Legislatures).](http://www.ncsl.org/research/elections-and-campaigns/2010-legislature-party-control-switch.aspx)] These state legislatures control the redistricting process which determines the geographical bounds of the districts from which members of the House of Representatives are elected. The 2012 elections are significant for two reasons: first, they were the first elections following the 2010 redistricting by Republican-dominated state legislatures; second, they were the first elections using district maps drawn after the Supreme Court’s decision in _Vieth v. Jubelirer_, in which the Court held that it could not discover a judicially manageable standard to adjudicate cases relating to partisan gerrymandering.^[Vieth v. Jubelirer, 541 U.S. 267 (2004).]  Thus, the 2012 elections were potentially affected by both a political  shift in the partisan control of the redistricting process and a legal shift in the practical permissibility of partisan gerrymandering. 

In the 2012 midterm elections, the Republican Party won only 49.4 percent of the national popular vote, but won 234 out of 435 seats (53.7 percent). In the 2010 election, prior to this post-_Vieth_, Republican-controlled round of redistricting, the Republican Party won 242 out of 435 seats (55.6 percent) with 53.5% of the vote. Via analysis accounting for uncontested elections and local factors, McGann et al. conclude that the 2010 redistricting resulted in roughly a 5% bias in favor of the Republican Party, meaning that “if the two parties win an equal number of votes, the Republicans will win 55% of the seats [... and] Democrats would have to win around 54% of the vote to have a fifty-fifty chance of winning control of the House.”^[@McGann-2016, 4.] The 2012 elections thus demonstrate the distortive effect of gerrymandering: simply by drawing lines, a minority party seized majority power. 

This distortion of representation clearly harms democratic legitimacy. Consider the aggregative proceduralist account of democratic legitimacy explored in `r newthought('section')` 3.1. Under this view, institutions are legitimate when they fairly aggregate their constituents’ beliefs and preferences into a group decision. Earlier, I proposed equality and neutrality as plausible conditions for fair procedures. To illuminate the harm caused by partisan gerrymandering, I will analyze it specifically with respect to each of these conditions. 

### Equality

The demand of equality is simple in single-level electoral procedures: all votes must be counted equally, and the candidate receiving the greater share of votes must prevail. In multi-stage representative procedures, it is less clear. Equality can only be assessed with respect to an identified relevant outcome. In multi-stage procedures, it is not immediately clear which outcome is relevant: the election of an individual representative or the actual actions of the legislature. I will argue that the legislature’s actual actions are the relevant outcomes and that the overall makeup of the legislature is a direct instrument toward these outcomes, and thus may be used a reference point for discussions of equality. 

If we consider the election of Congressional representatives to be the relevant group decision, then gerrymandering poses no threat to democratic legitimacy. No matter a district’s shape and no matter the intentional partisan distortion wrought by a state’s districting map, individual Congressional elections still fulfill the condition of equality. Consider North Carolina’s infamous 12th district, described as a “long, skinny squiggle that went all the way from Charlotte up to Greensboro.”^[[North Carolina’s extreme gerrymandering could save the House Republican Majority (Vox.com).](https://www.vox.com/policy-and-poli¬tics/2018/5/8/17271766/north-carolina-gerrymandering-2018-midterms-partisan-redistrict¬ing)]  Even in a district whose geometry itself reeks of bias, the formal condition of equality holds with respect to that district’s election of its representative. No interchanging of votes among individuals within the district could alter the outcome of the election.

But the election of each district’s Congressional representative is not the relevant outcome. Under the view that legitimacy derives from the fair aggregation of individual’s preferences into a collective decision, the election of a representative cannot be considered the final decision at issue. The concept of representative democracy itself shows why this cannot be the case. The election of a representative cannot be the ultimate outcome of representative democracy because representatives are not outcome but instead instruments within another aggregative institution. 

Unlike an executive, a representative has no unilateral power.^[References to the executive within this essay refer to a presidential executive, separate from the legislature with unilateral authority in at least some range of actions.]  Instead, they have power only through the representative institutions in which they serve and can bring about political outcomes only in combination with a majority of their fellow representatives. It may be sensible to conceive of the election of an executive as aggregation of preferences into an outcome. Although an executive is not an outcome _per se_, they can act unilaterally to effect certain outcomes and thus may be considered an independent and direct instrument to those outcomes. A representative, by contrast, is only a dependent and indirect instrument to the outcomes which constituents seek to achieve via their election. Thus, it makes little sense to say that the election of a representative aggregates constituents’ preference into an outcome. 

Instead, representatives are another instrument in the machine of aggregation. This is clearly evidenced by the structure of Congress---not a consortium of actors with independent power, but a venue for aggregation of representatives’ preferences, as derived from their constituents. Because elections of representatives are not means to an end but merely means to another means, these elections in isolation cannot be the proper site at which questions of fairness are assessed. To restrict analysis to only this first stage of the aggregative process would ignore the potential for unfairness in subsequent stages or in the relation between stages. Instead, we must consider the whole aggregative process. 

For discussions of gerrymandering, majority control of the legislature should be assessed as the relevant outcome. Like an executive, a party achieving majority status in a legislature is not actually an outcome, but it can be considered one because this majority, considered as a collective, is capable of acting unilaterally to effect outcomes, making it an independent and direct instrument to those outcomes. In this way, the majority status of a party not only represents a set of outcomes but is functionally equivalent to those outcomes.

Considering legislative majority as the relevant outcome allows us to examine the fairness of the process which selects this outcome. Although the condition of equality may be met with respect to each individual election, it is not met by the process as a whole. Geographic districting, by nature, tends to violate this condition. If political geography is not uniform---e.g., party A is concentrated in cities, party B is spread across rural areas---drawing geographic boundaries will almost always result in political inequality. 

To discuss equality in the context of a multi-stage aggregative process, equality must be defined more precisely. Equality as equal counted-ness, though a sufficient conception for single-stage procedures, fails in this context. Instead, equality should be understood in terms of practical ability to influence outcomes.^[_See_ @Tuck-2008 for an exploration of what it means for a vote to be effective. The discussion here is informed by Tuck’s conception of effectiveness as membership in an efficacious set of votes rather than as being the singular decisive vote.  _See also_ @Goldman-1968.] In a simple single-stage vote, this is synonymous with equal counted-ness. Each voter has an equal opportunity to cast an efficacious vote. The conceptions diverge in multi-district aggregative processes. Though all voters within a given district cast equally efficacious votes with respect to the election of their own representative, influence on the relevant outcome---control of the legislature---is unequal across districts. 

Voters in competitive districts---districts whose political geography gives candidates from either major party a fighting chance at victory---have a greater chance to impact the control of the legislature than do voters in safe districts, whose political geography all but ensures victory for one party over the other. By creating packed and cracked districts to disfavor the opposition party, gerrymandering intentionally creates unequal influence, leveraging disparate efficacy to distort the aggregative process. 

Closer analysis of geographic districting, however, reveals that unequal influence is likely to exist even without partisan gerrymandering. Unless specifically drawn to equalize competition, any set of geographic districting lines will create some districts more competitive than others, resulting in unequal influence of constituents across districts. This appears to suggest that geographic districting may be _per se_ incompatible with aggregative fairness. 

While this conclusion merits serious consideration, I do not propose to sustain this view. History, culture, and legal precedent in the United States display commitment to a geographic form of representation.^[Though a strong rejection of this view is not necessary in this essay, I do hope to engender some skepticism about the unusual (and, in my view, undeserved) credence granted to geographic considerations. The right to govern belongs to persons qua citizens of the polity, not as inhabitants of its districts. Further, to the extent that one’s particular geographic place has importance in the aggregative process, this importance must be diminished when the places in questions are nefariously drawn districts with the intent and effect of distorting the process of political representation. While citizens’ interests clearly vary across places and correlate within places, this is true of numerous other traits---race, gender, socioeconomic status, partisan affiliation, level of education, etc. The most (and perhaps only) cognizable reason for treating geography different than these other traits its visibility and historicity. We should not take this to be sufficient. Indeed, in the Voting Rights Act of 1964 and related jurisprudence, Congress and the courts recognized instead the importance of race, and it encouraged the usage of geographic districting to achieve the effects of racial districting. In choosing the trait across which districts are allocated, legislatures declare that trait to be of superseding importance as compared to other traits. As our society becomes more mobile and more communicatively connected, the claim that geography is of superseding importance becomes increasingly implausible. _See_ @Fishkin-2018, for a defense of geographic districting.] This leads to a dilemma: how can procedures value both equality and geography?

I propose a balancing test. Although we cannot respect geography while fully satisfying this stringent view of equality, we may be able to balance geographical interests against a notion of equality. Consider the following less stringent demand of equality: the design of aggregative procedures should not intentionally create inequality on the basis of traits not of genuine independent importance. Even if inequality need not be fully eliminated, there may be disallowable grounds for this inequality.

Having accepted for the sake of argument the independent importance of geography, this condition of equality allows geographic districting but does not allow intentionally diluting or enhancing the aggregate power of voters along any other lines---e.g., partisan affiliation. Partisan gerrymandering clearly violates this conception of equality. Gerrymandering treats individuals disparately with respect to partisan affiliation (actual or imputed) by creating landslide victories and close losses for the disfavored party and creating close victories and landslide losses for the favored party in excess of would result from districting simply with regard to geography. This results in dilution of votes for one party and amplification of votes for the other, but so does geography itself. Parsing disallowed inequality from its permissible counterpart requires reference to a range of naturally expected outcomes resultant from legitimate interests such as geography. 

### Neutrality

It appears intuitively apparent that political gerrymandering constitutes a violation of neutrality. Detecting this non-neutrality, however, proves challenging. A gerrymandered aggregative procedure does not favor one party over another in their capacities as political parties. Rather, it does so through political geography. The favored Party A is not favored by nature of being Party A but instead by nature of occupying a particular geographic distribution. Any party with the same geographic traits as Party A would enjoy the same advantage. 

This illustrates a difficulty in addressing gerrymandering. It is neutral in a technical sense with respect to the parties as such, only violating neutrality with respect to parties’ political geography. In embracing geographic representation, we are committed to endorsing a certain degree of geographic non-neutrality. Geography itself is not neutral between outcomes. Particularly extreme or arbitrary geographic non-neutrality, however, may reveal itself to be a mere pretext for partisan non-neutrality. Considering this, accusations of gerrymandering can only be sustained via reference to the natural distribution of possible outcomes.

## Corruption of Deliberation

Beyond its distortive harm to the aggregative function of democracy, gerrymandering also threatens the key deliberative and epistemic functions of democracy. The aggregative function of democracy is the process by which individuals’ preferences are aggregated to a group decision. While the aggregative function takes preferences and beliefs as given inputs to the discovery of a group decision, the deliberative function is a constructive function which concerns the formation of these preferences. 

Aggregation occurs through voting---citizens voting for representatives, representatives voting for policies. The deliberative function of democracy occurs through public discourse, but this discourse is not fully independent of the structure of aggregative processes. In encountering the political views and expression of others, citizens are forced to examine and justify those that they themselves hold. This process of encounter and examination serves to enhance the quality of the preferences, which are later taken as inputs by democracy’s aggregative function, by encouraging citizens to generate and consider factual and moral arguments in defense of political preferences. This is clearly a more abstract and less quantifiable process than aggregation, but it is nonetheless important to democracy. While it is clear how gerrymandering corrupts aggregation---it is directly related to the aggregative process of voting---it is less clear how it corrupts the deliberative process. 

The current of public discourse runs throughout life in democratic society. However, it is significantly agitated and particularized by the occurrence of contested elections. While one can hardly avoid discussing political issues on occasion, they do not necessarily do so with great intensity or specificity. Contested elections---opportunities to make real political choices with real consequences---bring political issues into the lives of citizens with urgency and specificity otherwise unavailable. As such, they encourage forms of discourse rarely found elsewhere, thus enhancing the deliberative and epistemic functions of democracy. 

Gerrymandering distorts deliberation by restricting the sites of electoral competition. By creating vast supermajorities for the disfavored party in a select few districts and closer (but still safe) margins of victory for the favored party in the rest, gerrymandering reduces the extent of electoral contestation. Electoral contestation arouses deeper, more precise, and more meaningful public discourse. By restricting contested elections to only a few (or ideally zero) districts, gerrymandering reduces the incidence of meaningful public discourse, thus inhibiting the proper formation of political preferences. 

Further, by privileging some districts’ competitiveness over others, gerrymandering elevates the issues salient to some constituents while silencing issues salient to the rest. Political discourse is not only restricted in depth, but also redirected in content. The pivotal issue, on which an election’s outcome may turn, varies across districts. For example, taxation may be the pivotal issue in a district containing both a wealthy suburb and an impoverished inner-city neighborhood. By contrast, environmental regulation and the future of the coal industry may the pivotal issue in a district in the Appalachian region, populated by coal miners and outdoors enthusiasts. Because a scheme of gerrymandering will create some districts far more competitive than others, it will elevate some districts’ pivotal issues to the forefront of political discourse, while suppressing those of other districts. As a result, gerrymandering not only reduces the amount of productive deliberation, but also distorts the focus of the deliberation which does occur, undermining deliberative legitimacy through two distinct channels. 

Having described the ways in which gerrymandering threatens democracy and harms its procedural legitimacy and having previously identified a narrow range of legitimacy-enhancing process-oriented judicial review, I will discuss in the following section how this theory of judicial review may be applied to partisan gerrymandering. 

The legitimacy-enhancing process-oriented conception of judicial review explored in `r newthought('section')` 3 identifies judicial review as permissible when two constraints are fulfilled.

1. The legislative or executive action overruled constitutes a significant harm to procedural democratic legitimacy.
2. Resolution of the key question at issue does not require resolving questions on which there is serious substantive disagreement. 

In this section, I will argue that both of these constraints are satisfied with respect to partisan gerrymandering and respond to several potential objections. 

## Procedural Harm

`r newthought('Section')` 4 establishes the key procedural harms caused by gerrymandering: first, it undermines aggregative procedural legitimacy by violations conditions of equality and neutrality; second, it corrupts deliberative procedural legitimacy by reducing the depth and redirecting the content of political discourse, thus damaging the constructive functions of democracy. Judicial review of partisan gerrymandering would allow the court to provide relief for these harms.

## Substantive Disagreement

To show that harm may be undone is insufficient to justify an act of judicial review. These acts, by their nature rather than their effects, cause harm entirely separate from that which they relieve. The harm done must be significantly outweighed by the harm undone. In such a non-quantifiable matter, no narrow case can be compellingly determinate. For these reasons, I will endeavor to show that the harm to democratic legitimacy is much less than in most instances of judicial review because the issue of gerrymandering invokes lesser issues of disagreement. 

Consider the case of abortion, a central case of political disagreement. The pro-choice position holds that women enjoy a fundamental right of bodily autonomy, barring any legislative intervention regarding medical procedures to terminate a pregnancy. The pro-life position holds that developing fetuses enjoy a right to life, not allowing legislatures to prohibit medical abortions but in fact compelling them to do so. Each position proceeds from a sincere substantive commitment, and the two positions are wholly irreconcilable. Further, each position enjoys strong support. This disagreement, per Waldron’s argument, necessitates that the issue of abortion be decided by democratic processes. Court intervention in the form of judicial review would constitute grave harm to procedural democratic legitimacy. 

Now consider the case of gerrymandering. Though broadly condemned, gerrymandering is not without its proponents. In a legislative hearing on districting, North Carolina General Assembly Representative David Lewis implored the legislature to engage in pro-Republican gerrymandering: “I propose that we draw the maps to give a partisan advantage to 10 Republicans and 3 Democrats because I do not believe it’s possible to draw a map with 11 Republicans and 2 Democrats [and because] I think electing Republicans is better than electing Democrats.”^[[Supreme Court Sends Case on North Carolina Gerrymandering Back to Lower Court (Washington Post).](https://www.washingtonpost.com/politics/courts_law/supreme-court-sends-case-on-north-carolina-gerrymandering-back-to-lower-court/2018/06/25/03c1119e-787e-11e8-93cc-6d3beccdd7a3_story.html?utm_term=.d731852e2399)]

But even here, the disagreement between pro-gerrymandering Representative Lewis and the anti-gerrymandering public is of a somewhat different nature than disagreement on abortion. The pro-life position proceeds from sincere commitment to the belief that abortion is wrong and must be prohibited, and the pro-choice position proceeds from sincere commitment to the belief that interfering with women’s bodily autonomy is wrong and must be prohibited. Representative Lewis’ pro-gerrymandering position does not proceed from a similarly sincere commitment. He does not claim that gerrymandering is right _per se_ and thus must guide the legislature’s districting. Instead, he claims that we should advantage Republicans over Democrats and engage in gerrymandering to achieve this end. His position includes no commitment to the rightness of gerrymandering itself. Instead, his support for gerrymandering is wholly derivative from his commitment to Republican partisan positions.

Lewis’ position may not coincide perfectly with other pro-gerrymandering positions, but analyzing his position leads us to an important question: what is the principal disagreement between pro- and anti-gerrymandering positions?  Attempting to answer this question reveals the absurdity of an actual pro-gerrymandering position. The key disagreement between Lewis and those who demand a fairer districting map is not a matter of substance but instead a matter of control. Lewis’ position is not genuinely pro-gerrymandering; it is simply pro-Republican. A genuine pro-gerrymandering position would have to support pro-Democratic gerrymandering where Democrats enjoy legislative control and pro-Republican gerrymandering where Republicans are in power. The only possible basis for this view is a commitment to a fiercely undemocratic principle: that the dominance those in power should continually increase at the expense of those out of power. 

Questions of gerrymandering are ultimately not about the substance of politics. When two parties disagree about a particular instance of gerrymandering, they are actually disagreeing about the underlying substantial issues to which gerrymandering serves a tactical function. There is no principled position in support of gerrymandering _per se_ and debates on gerrymandering turn fully on political tactics rather than political substance, so there is only minimal harm done to democracy when this disagreement is resolved judicially rather than legislatively. Because judicial review of gerrymandering substantially ameliorates a harm to the political process at a minimal expense, judicial review of partisan gerrymandering enhances democratic legitimacy.  

# Towards a Manageable Standard

`r newthought('My argument')` to this point has sought to establish the legitimacy of judicial review of partisan gerrymandering. I have yet to suggest a coherent approach for doing so. Many who would accept all of my argument to this point would reject my conclusion because, they insist, no coherent approach exists for adjudication. In _Vieth v. Jubelirer_, Justice Scalia, in an opinion joined by Chief Justice Rehnquist and Associate Justices O’Connor and Thomas, wrote that “no judicially discernible and manageable standards for adjudicating political gerrymandering claims” could be found.^[Vieth v. Jubelirer, 541 U.S. 267, 281 (2004).] Justice Kennedy, whose refusal to join Justice Scalia’s opinion narrowly prevented the issue of partisan gerrymandering being foreclosed from future consideration by stare decisis, held out hope for a workable standard: “That no such standard has emerged in this case should not be taken to prove that none will emerge in the future.”^[Vieth v. Jubelirer, 541 U.S. 267, 311 (2004).] The Court’s future rulings on political gerrymandering will almost certainly turn on the presence---or lack---of a workable standard. In searching for such a standard, the above discussion of democratic legitimacy will play a key role guiding role. 

## Challenges for a Workable Standard

Crafting judicially manageable standards, particularly for constitutional issues, is rarely an easy task. The presence of many interlocking interests necessitates balancing tests, often in multiple parts. Separating intent and effect mandates standards that look beyond readily apparent empirical facts. The judicially disliked arbitrariness of harsh cutoffs leads to blurry thresholds. All of these difficulties afflict gerrymandering jurisprudence. The state’s interest in controlling its elections must be balanced against the general interest in fairness. Because fair districting is not the default result of a geographic districting process, intent must be examined or inferred. The range of distortion possible from gerrymandering may necessitate some threshold to distinguish permissible from impermissible, but a numeric cutoff seems distasteful for a very text-oriented judiciary. Justice Kennedy writes^[Vieth v. Jubelirer, 541 U.S. 267, 281 (2004), 311.] 

> If a State passed an enactment that declared “All future apportionment shall be drawn so as most to burden Party X's rights to fair and effective representation, though still in accord with one-person, one-vote principles,” we would surely conclude the Constitution had been violated.

From Justice Kennedy’s example, we see that clearly there exist potential acts which can be competently and confidently identified as impermissible partisan gerrymandering. The difficult matter is to discern those cases from the rest. 

An additional challenge for a workable standard stems from the Court’s finding that the plaintiffs in _Gill v. Whitford_ failed to demonstrate standing---i.e., the legal right to bring suit. Per the Court’s opinion in _Lujan v. Defenders of Wildlife_, synthesizing centuries of standing doctrine, plaintiffs must show that they “have suffered [...] invasion of a legally protected interest which is (a) concrete and particularized [...] and (b) actual or imminent.”^[Lujan v. Defenders of Wildlife, 504 U.S. 555, 560 (1992). Internal quotations omitted.]  To be considered particularized, an injury “must affect the plaintiff in a personal and individual way.”^[Lujan v. Defenders of Wildlife, 504 U.S. 555, 560 (1992).]  The Court’s opinion in Gill found that the methods and metrics offered by the plaintiffs had failed to provide the “requisite proof” of a “personal stake in the case,” emphasizing that any viable standard in future cases must be oriented to particularized, rather than generalized, harm---i.e., harm to individuals, not political parties.^[Gill v. Whitford, 585 U.S. __ (2018) (138 S. Ct. 1916).]

Having described several of the difficulties in crafting a standard for partisan gerrymandering cases, I will assess the relative merits of several proposed standards in search of one that satisfies the Court’s demands. 

## The Efficiency Gap

To devise a standard for adjudicating gerrymandering one must first consider what about gerrymandering is wrong. The efficiency gap, a standard proposed by Nicholas Stephanopoulos and Eric McGhee, proceeds from a recognition of partisan bias as the prime evil of gerrymandering. Noting that the Court has expressed openness to the idea of partisan symmetry---“treat[ing] the major parties symmetrically in terms of the conversion of votes to seats”---they devise a standard related to this.^[@Stephanopoulos-2014 at 831.] 

Stephanopoulos and McGhee note that “the goal of a partisan gerrymander is to win as many seats as possible given a certain number of votes” by maximizing the efficiency of votes for one’s own party and maximizing the inefficiency of votes for the other party.^[@Stephanopoulos-2014 at 850.]   A vote is inefficient, or “wasted,” when it is cast for a losing candidate or for a winning candidate “in excess of what the candidate[] needed to prevail.”^[@Stephanopoulos-2014.]  A plurality-rule, single-member-district system will always result in many inefficient votes. One cannot eliminate wasted votes; instead, the goal is “to end up with fewer wasted votes than the opposition by winning […] seats by smaller margins [and losing seats by larger margins] on average.”^[@Stephanopoulos-2014.]  This minimizes the favored party’s wasted votes (and maximizes the other party’s wasted votes) via two channels: first, winning by small margins minimizes the party’s unnecessary votes cast for winning candidates and maximizes the opposition’s fruitless votes cast for candidates who end up losing narrowly; second, losing by large margins minimizes unnecessary votes cast for the party’s losing candidates and maximizes redundant votes cast for the opposition’s winning candidates. 

The efficiency gap---proposed as a quantitative measure of the extent of gerrymandering---is “the difference between the parties’ respective wasted votes, divided by the total number of votes cast in the election.”^[@Stephanopoulos-2014 at 851. Stated equivalently: ] 
```{marginfigure}
$EG = \frac{Wasted Votes_{p1} - Wasted Votes_{p2}}{TotalVotes}$ 
```
```{marginfigure}
Because U.S. elections require districts of equal population and often only two major parties, the efficiency gap may also be calculated more easily, without tabulating the total wasted votes across the state as follows: 
```
```{marginfigure}
$EG = Seat Margin - (2*Vote Margin)$.
```
As the name suggests, it measures the difference in efficiency between the two parties in converting votes to seats. When the efficiency gap is significantly greater than zero, favoring one party over another, politics occurs not on a level playing field, but instead along a hillside: the gerrymandering party is allowed to play downhill while the opposition fights an uphill battle. 

This standard, the authors claim, measures “the essence of what critics have in mind when they refer to partisan gerrymandering” and “identifies a concrete harm worthy of judicial intervention.”^[@Stephanopoulos-2014 at 852--853.]  The Court considered this metric in _Gill v. Whitford_ but ultimately made no proclamation of its view. In oral argument, Chief Justice Roberts expressed skepticism of the standard on the basis that it ultimately reduced to proportional representation.^[[Gill v. Whitford, Oral Argument Transcript, U.S. Supreme Court, 3 October 2017, no. 16-1161](https://www.supremecourt.gov/oral_arguments/argument_transcripts/2017/16-1161_bpm1.pdf), 41:1–14.] Mira Bernstein and Moon Duchin demonstrate mathematically that the efficiency gap, although it takes wasted votes as inputs, essentially only measures “deviation from double-proportionality of votes to seats.”^[@Bernstein-2017. “Double-proportionality of votes to seats” means that a 50-50 vote should result in a 50-50 seat allocation, a 60-40 vote should result in a 70-30 seat allocation, and a 70-30 vote should result in a 90-10 seat allocation. ] While deviance from proportionality may be a strong indicator of gerrymandering, it cannot be the basis for a standard of adjudication. Enforcing a prohibition on partisan gerrymandering via such a standard would amount to the enforcement of approximate double-proportionality. Though it did not explicitly reject the efficiency gap as a standard, the Court has expressed reticence to enforcing proportionality or any similar decree of the appropriate seat-vote relationship.  

The efficiency gap succeeds in measuring the essence of gerrymandering’s function. It does not, however, succeed in measuring the essence of its harm. Further, it does not identify harm to individuals, but instead only demonstrates harm to parties and to procedural fairness. Though the harm to procedural fairness (and thus legitimacy) is a crucial component of the justification for judicial intervention on the issues of partisan gerrymandering, it is not a sufficient basis for a standard of adjudication. A workable standard must show specific individuals who are harmed. To do so, it cannot merely assess the state-wide fairness of a map, but instead must identify specific unfair districts, the shape of which harms their constituents in the service of an illegitimate political end. 

Though the efficiency gap proves insufficient as a standard, it has value as a metric. The partisan unfairness which it measures, while insufficient on its own, may prove a useful part of a more comprehensive test. 

## Statistical Outliers

The issue of gerrymandering, by nature of its delicate interaction with political geography, evades detection and adjudication by simple standards of equal pith and obviousness as the “one person, one vote” standard applied in apportionment cases. Unlike this clear command of equal population in apportionment, there is no obvious ideal districting paradigm, deviation from which must be constrained. Recognizing this, the Metric Geometry and Gerrymandering Group, led by mathematician Moon Duchin and computer scientist Justin Solomon, have developed a method based not around an ideal paradigm but instead around a statistical projection of the ensemble of feasible districts. Rather than accepting an abstract ideal benchmark and measuring deviance, they build a distribution of possible maps and identify outliers. 

Creating a distribution of all possible districting maps, however, seems impossible. With current computing capabilities, it probably is. There are 706,152,947,468,301 different ways to partition a nine-by-nine grid---a figure many orders of magnitude simpler than any U.S. state---into equally sized rook-contiguous districts. Identifying all of these possibilities would take a high-performance computer over a week.^[@Duchin-2018 For a district to be “rook contiguous,” each square in the district must be accessible from another square via a legal move by a rook in chess---i.e., a move north, south, east, or west.] For North Carolina, there are an estimated $10^{80}$ possible districting maps.^[[Can Statistics Solve Gerrymandering? (FiveThirtyEight Politics Podcast)](https://fivethirtyeight.com/features/politics-podcast-can-statistics-solve-partisan-gerrymandering/), 5:55.] To project all of these would be an impossible feat of computing. Modern mathematical and statistical methods provide a possible alternative. 

### Markov chain Monte Carlo modeling

Statistical modeling via a Markov chain Monte Carlo (MCMC) method can generate an ensemble of districting maps which is representative of the universe of all possible districts. An MCMC method employs “algorithmic sampling to understand the space of all possible districts for a given state.”^[[Moon Duchin, “Gerrymandering Metrics: How to Measure? What’s the Baseline?”](https://arxiv.org/abs/1801.02064). _See_ @Diaconis-2009 for a more complete discussion of this methodology and its applications.] Ordinary Monte Carlo methods use random sampling to represent objects---such as the space of all possible North Carolina district plans---which cannot be fully computed. In the case of gerrymandering, this would involve taking a list of census blocks of precincts as inputs and randomly assigning them to districts. This method, however, produces valid districting plans (i.e., plans which satisfy state requirements, such as contiguity, compactness, competitiveness, or North Carolina’s “whole county provision”) only at a very low probability---hence, the introduction of a Markov chain. 

MCMC, rather than generating random plans from scratch, takes a valid districting plan as its starting point and randomly modifies it by randomly selecting two census blocks and then interchanging them, if the resulting district map will also be valid. Each new districting plan is added to the sample. This random procession from a districting plan to a slight variant (repeated as needed) can be characterized as a Markov chain. The sample created by this random walk---through millions, if not billions of iterations---is representative of the overall space which it attempts to model.^[_See_ [MCMC on a 7 x 7 Grid (Metric Geometry and Gerrymandering Group)](https://mggg.org/metagraph/7x7.html) for a digestible explanation and exploration of this method.]

### Advantages of a statiscal standard

The MCMC method has three key features to recommend its usage: first, it considers the legal, political, and geographical differences between states; second, it identifies individualized harm, rather than generalized state-wide harm; third, it avoids the threshold problem. 
The non-neutrality of partisan gerrymandering is channeled through geography and inseparable from the non-neutrality of legal and geographic considerations unique to each state. Because of this, a workable standard for adjudicating these cases must consider factors which are distinct among states. Rather than proposing one universal benchmark against which gerrymanders are to be measured (e.g., proportionality or partisan symmetry) a workable standard must allow the benchmark to adapt to the particular features of the state at issue. 

Consider Massachusetts: although Republican candidates for the House of Representatives often receive up to 40% of the state-wide vote share, no Republican has won a seat since 1994. Though this may seem at first like a prime case of pro-Democratic gerrymandering, it is in fact the only possible outcome. Duchin _et al._ demonstrate that, due to Massachusetts’ fairly uniform political geography, it would be impossible for Massachusetts legislators to draw even a single Republican district.^[[Moon Duchin et al, "Locating the Representational Baseline: Republicans in Massachusetts."](https://arxiv.org/abs/1810.09051)]   

The MCMC method, rather than proposing a singular benchmark, explores a given state’s geography, districting laws, and voting patterns via random progression and algorithmic sampling and generates a range of expected outcomes---i.e., seat allocations to each party given a particular voting pattern---particular to that state. The distribution of these outcomes generally approximates a bell-curve, and the peak of the bell curve may be interpreted as the neutral benchmark against which districting plans can be measured. An outlier map favoring the party that drew the map provides clear evidence of partisan gerrymandering.  

Due to the requirements for legal standing, a workable standard cannot merely identify state-wide unfairness. Instead, it must enable individual plaintiffs in specific districts to show that their votes were intentionally diluted in service of partisan bias. Dilution can be understood as the proportion of votes in one’s district which are not part of the efficacious set which brings about an electoral victory. In a 60-39 election, 50 of the 60 votes cast for the winning candidate are efficacious in bringing out their victory, while 10 are superfluous. All 39 votes cast for the losing candidate, because they did not bring about an electoral victory, are ineffective.^[@Tuck-2008, 44.]  Packing and cracking, by increasing the proportion of ineffective votes for the disfavored party, constitute vote dilution. A claim that one’s vote was diluted, either by packing or cracking, is empty without reference to a benchmark. 

One potential (but ultimately unworkable) benchmark is the overall state-wide vote proportion.  This benchmark would identify packed and cracked districts as those which deviate significantly from the overall state-wide vote proportion, thus compelling the state to roughly equalize the vote proportion across districts. In the case of, e.g., a 60-39 election, this leads to a clearly undesirable outcome. If districts are drawn so that each resembles the overall state-wide vote breakdown, the majority party will win not a roughly proportional three fifths of the state’s seats but instead every seat. Further, this standard renders geographic considerations nearly impossible.

The MCMC method provides a viable alternative method. For a given address (representing an individual plaintiff), MCMC can generate a distribution of the possible vote shares in hypothetical districts which would include this address. When a constituent’s district is transformed from one which in which their preferred candidate would enjoy a relatively narrow victory to one where they would win in a landslide, their vote is diluted. A constituent’s vote is similarly diluted when their district is transformed from one where their preferred candidate has a chance at victory to where their preferred candidate is very likely to lose. 

By generating a distribution of the possible vote shares in a representative sample of districts, MCMC generates the natural range of vote dilution. Outliers from this distribution are very likely to be cases of intentional partisan vote dilution, rather than just natural consequences of geography. Because this method creates a benchmark which considers a state’s actual geography, it enables courts to distinguish intentional dilution from incidental dilution. Intentional vote dilution, identified as an outlier from the expected vote dilution distribution, can serve as proof of particularized harm, as is required for standing. 

Further, MCMC is much less vulnerable to the threshold problem than other standards. An attempt to administer a standard defined with regard to partisan fairness must declare a maximum allowable level of unfairness. Any such numerical threshold will necessarily be arbitrary, and the declaration thereof will encourage manipulation all the way up to that threshold. Unlike a standard focused on partisan fairness, MCMC provides evidence of intentional distortion relative to a natural range of outcomes. As such, no threshold is necessary. MCMC provides actual evidence of gerrymandering, which may be considered alongside other evidence and tested against whichever evidentiary standard the court deems proper.  

Because MCMC outlier analysis enables the identification of partisan gerrymandering without imposing an unfounded ideal of fair districting, empowers plaintiffs to demonstrate individualized harm in specific districts, and avoids the threshold problem, it can serve as a workable standard for cases of partisan gerrymandering. 

# Conclusion

`r newthought('In this')` paper, I have argued in favor of judicial review of partisan gerrymandering. The primary first-order objection---that judicial review diminishes democratic legitimacy---is defeated by a process-oriented legitimacy-enhancing theory of judicial review. The second-order objection---that there is no manageable standard to discern gerrymandering from natural geographic distortion---is defeated by the usage of Markov chain Monte Carlo modeling to identify outliers from natural distributions. However, just as technology newly enables us to identify partisan gerrymandering, it also allows gerrymandering to be practiced with increasing efficacy. The two cases currently before the Supreme Court likely provide its last chance to address this issue before the round of redistricting following the 2020 census. The future of democratic representation is in the hands of nine Justices in black robes. Faith to democratic legitimacy commands that they protect it. 

# Bibliography
